{
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "plugins": [
    "html",
    "react",
    "markdown"
  ],
  "env": {
    "browser": true,
    "node": true
  },
  "parser": "@babel/eslint-parser",
  "globals": {
    "Promise": false
  },
  "rules": {
    "no-console": 2,
    "comma-dangle": [
      "error",
      "never"
    ],
    "max-len": [
      "error",
      {
        "code": 80,
        "comments": 80,
        "ignoreUrls": true,
        "tabWidth": 2,
        "ignorePattern": "^import"
      }
    ],
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "quotes": [
      "error",
      "single",
      {
        "allowTemplateLiterals": true
      }
    ],
    "semi": [
      "error",
      "always"
    ],
    "one-var": [
      "error",
      "never"
    ],
    "no-confusing-arrow": "error",
    "no-unused-vars": [
      "error",
      {
        "ignoreRestSiblings": true
      }
    ],
    "key-spacing": [
      "error",
      {
        "beforeColon": false,
        "afterColon": true
      }
    ],
    "react/jsx-tag-spacing": [
      "error",
      {
        "beforeSelfClosing": "always"
      }
    ],
    "react/jsx-no-target-blank": [
      0
    ],
    "space-infix-ops": [
      "error",
      {
        "int32Hint": false
      }
    ],
    "require-jsdoc": [
      "error",
      {
        "require": {
          "FunctionDeclaration": true,
          "MethodDefinition": true,
          "ClassDeclaration": true,
          "ArrowFunctionExpression": true
        }
      }
    ]
  },
  "settings": {
    "react": {
      "version": "17.0.1"
    }
  }
}
