version: '3.7'

services:
  viewer:
    container_name: ddd_viewer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  nginx:
    build:
      context: nginx/
    ports:
      - 80:80
    depends_on:
      - viewer