/**
 * @constant CesiumToken The CesiumToken generated by https://cesium.com/ion/tokens
 */
export const CesiumToken =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTk4OGI5Ny0wZDZkLTQ1YWYtYWNjZi0xZGIzZGRiMDhjMTkiLCJpZCI6NDMwMCwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTU2OTQ4ODEwNH0.vlHoIIaINsSQC4nlYqFbzTOBLIRxOXjz1T2oPcwI7-o";

export default CesiumToken;
