FROM nginx:1.17.2-alpine
LABEL maintainer Michael Holthausen <holthausen@terrestris.de>
#-------------Application Specific Stuff ----------------------------------------------------

COPY default.conf /etc/nginx/conf.d/