/**
 * @constant cesiumToken The CesiumToken generated by https://cesium.com/ion/tokens for info@terrestris.de
 */
export const cesiumToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwMzg3NGI3NC01ZGYzLTRmYzMtY' +
  'TkzZS00ZjM0NTczYmY5NjciLCJpZCI6MjMwOTgsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQ' +
  'iOjE1ODI3MjQzNDN9.P-EMnYp2aNjz2S6v5MQIWK0FiIBNlOCRhJeT-U5e84I';

export const customer = {
  title: 'WorldMap 3D'
};

export const viewerConfig = {
  geocoder: true,
  skyAtmosphere: false,
  shouldAnimate: false,
  animation: true,
  baseLayerPicker: true,
  fullscreenButton: false,
  homeButton: true,
  infoBox: false,
  sceneModePicker: true,
  selectionIndicator: true,
  navigationHelpButton: true,
  imageryProvider: false,
  skyBox: false
};

export const imageFile = {
  source: './img/custom/dom_sued.jpeg'
};

export const wms_nw_dop = {
  url: 'https://www.wms.nrw.de/geobasis/wms_nw_dop',
  layers: 'nw_dop_rgb',
  parameters: {
    format: 'image/png',
    transparent: 'true'
  }
};

export const czml_cgn_cathedral = [
  {
    id: 'document',
    name: 'Location of Photobox',
    version: '1.0'
  },
  {
    id: 'babylonIdCologneCathedral',
    name: 'Cologne Cathedral',
    position: {
      cartographicDegrees: [6.95798, 50.940679, 58]
    },
    ellipsoid: {
      radii: {
        cartesian: [5.0, 5.0, 5.0]
      },
      material: {
        solidColor: {
          color: {
            rgba: [255, 0, 0, 255]
          }
        }
      }
    }
  }
];

export const tunnelsFile = './data/tunnels.glb';

export default cesiumToken;
