/**
 * @constant cesiumToken The CesiumToken generated by https://cesium.com/ion/tokens for info@terrestris.de
 */
export const cesiumToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIw' +
'Mzg3NGI3NC01ZGYzLTRmYzMtYTkzZS00ZjM0NTczYmY5NjciLCJpZCI6MjMwOTgsInNjb3BlcyI6' +
'WyJhc3IiLCJnYyJdLCJpYXQiOjE1ODI3MjQzNDN9.P-EMnYp2aNjz2S6v5MQIWK0FiIBNlOCRhJe' +
'T-U5e84I';
;

export const customer = {
  title: 'WorldMap 3D'
};

export const viewerConfig = {
  geocoder: true,
  skyAtmosphere: false,
  shouldAnimate: false,
  animation: true,
  baseLayerPicker: false,
  fullscreenButton: false,
  homeButton: true,
  infoBox: false,
  sceneModePicker: true,
  selectionIndicator: true,
  navigationHelpButton: true,
  imageryProvider: false,
  skyBox: false
};

export const wms_nw_dop = {
  url: 'https://www.wms.nrw.de/geobasis/wms_nw_dop',
  layers: 'nw_dop_rgb',
  parameters: {
    format: 'image/png'
  }
};

export const czml_cgn_cathedral = [
  {
    id: 'document',
    name: 'Location of Photobox',
    version: '1.0'
  },
  {
    id: 'babylonIdCologneCathedral',
    name: 'Cologne Cathedral',
    position: {
      cartographicDegrees: [6.9568, 50.941287, 105.0]
    },
    ellipsoid: {
      radii: {
        cartesian: [5.0, 5.0, 5.0]
      },
      fill: true,
      material: {
        solidColor: {
          color: {
            rgba: [255, 0, 0, 255]
          }
        }
      }
    }
  }
];

export default cesiumToken;
