/**
 * @constant cesiumToken The CesiumToken generated by https://cesium.com/ion/tokens for info@terrestris.de
 */
export const cesiumToken: string =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwMzg3NGI3NC01ZGYzLTRmYzMtY' +
  'TkzZS00ZjM0NTczYmY5NjciLCJpZCI6MjMwOTgsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQ' +
  'iOjE1ODI3MjQzNDN9.P-EMnYp2aNjz2S6v5MQIWK0FiIBNlOCRhJeT-U5e84I';

export const customer = {
  title: 'WorldMap 3D'
};

export const BASE_PATH: string = import.meta.env.BASE_URL;

// External data URL for large assets (terrain and tilesets)
export const EXTERNAL_DATA_URL: string = import.meta.env.VITE_EXTERNAL_DATA_URL || `${BASE_PATH}data/`;

export const viewerConfig = {
  geocoder: true,
  skyAtmosphere: false as false,
  shouldAnimate: false,
  animation: true,
  baseLayerPicker: true,
  fullscreenButton: false,
  homeButton: true,
  infoBox: false,  // Disable native InfoBox to use custom one
  sceneModePicker: true,
  selectionIndicator: true,
  navigationHelpButton: true,
  imageryProvider: false as false,
  skyBox: false as false
};

export const imageFile = {
  source: `${BASE_PATH}img/custom/dom_sued.jpeg`
};

export const wms_nw_dop = {
  url: 'https://www.wms.nrw.de/geobasis/wms_nw_dop',
  layers: 'nw_dop_rgb',
  parameters: {
    format: 'image/png',
    transparent: 'true'
  }
};

export const czml_cgn_cathedral = [
  {
    id: 'document',
    name: 'Location of Photobox',
    version: '1.0'
  },
  {
    id: 'babylonIdCologneCathedral',
    name: 'Cologne Cathedral',
    position: {
      cartographicDegrees: [6.95798, 50.940679, 58]
    },
    ellipsoid: {
      radii: {
        cartesian: [5.0, 5.0, 5.0]
      },
      material: {
        solidColor: {
          color: {
            rgba: [255, 0, 0, 255]
          }
        }
      }
    }
  }
];

export const tunnelsFile: string = `${BASE_PATH}data/tunnels.glb`;

export const tilesetUrl: string = `${EXTERNAL_DATA_URL}tiles-test/tileset.json`;

export const terrainFile: string = `${EXTERNAL_DATA_URL}geotiff-terrain-output/`;

export const wms_dwd_radar = {
  url: 'https://maps.dwd.de/geoserver/dwd/ows',
  layers: 'dwd:Niederschlagsradar',
  parameters: {
    SERVICE: 'WMS',
    VERSION: '1.3.0',
    FORMAT: 'image/png',
    TRANSPARENT: true
  }
};

export default cesiumToken;
